# Generated by Django 4.2 on 2026-04-27 13:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetUrbain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('nombre_familles', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('taille_moyenne_famille', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('surface_terrain', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
                ('niveau_budget', models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('élevé', 'Élevé')], max_length=10)),
                ('priorite', models.CharField(choices=[('logements', 'Logements'), ('espaces_verts', 'Espaces verts'), ('services_publics', 'Services publics'), ('équilibré', 'Équilibré')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projet Urbain',
                'verbose_name_plural': 'Projets Urbains',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PropositionAmenagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_logements', models.IntegerField()),
                ('nombre_ecoles', models.IntegerField()),
                ('nombre_centres_sante', models.IntegerField()),
                ('nombre_marches', models.IntegerField()),
                ('surface_espaces_verts', models.FloatField()),
                ('surface_routes', models.FloatField()),
                ('description', models.TextField()),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('projet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposition', to='urban_design.projeturbain')),
            ],
            options={
                'verbose_name': "Proposition d'aménagement",
                'verbose_name_plural': "Propositions d'aménagement",
            },
        ),
        migrations.CreateModel(
            name='ImageGeneree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('url_image', models.URLField(blank=True, null=True)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_generees', to='urban_design.projeturbain')),
            ],
            options={
                'verbose_name': 'Image générée',
                'verbose_name_plural': 'Images générées',
                'ordering': ['-date_generation'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('creation', 'Création du projet'), ('modification', 'Modification du projet'), ('suppression', 'Suppression du projet'), ('proposition_generee', 'Proposition générée'), ('proposition_regeneree', 'Proposition regénérée'), ('prompt_genere', 'Prompt image généré')], max_length=30)),
                ('description', models.TextField()),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='urban_design.projeturbain')),
            ],
            options={
                'verbose_name': 'Historique du projet',
                'verbose_name_plural': 'Historiques des projets',
                'ordering': ['-date_action'],
            },
        ),
    ]
