# Generated by Django 4.2 on 2026-05-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban_design', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegeneree',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='generated_images/'),
        ),
        migrations.AddField(
            model_name='imagegeneree',
            name='statut',
            field=models.CharField(choices=[('prompt_only', 'Prompt uniquement'), ('image_generated', 'Image générée')], default='prompt_only', max_length=30),
        ),
        migrations.AlterField(
            model_name='historiqueprojet',
            name='action',
            field=models.CharField(choices=[('creation', 'Création du projet'), ('modification', 'Modification du projet'), ('suppression', 'Suppression du projet'), ('proposition_generee', 'Proposition générée'), ('proposition_regeneree', 'Proposition regénérée'), ('prompt_genere', 'Prompt image généré'), ('image_generee', 'Image générée')], max_length=30),
        ),
    ]
